spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:h2:mem:testdb
    user: sa
    password:

logging:
  level:
    org.springframework: INFO
    com.github.juanbarbosa: DEBUG

server:
  servlet:
    context-path: /auth